<script lang="ts">
	import OperatorGuard from '$lib/components/OperatorGuard.svelte';import PlatformNav from '$lib/components/PlatformNav.svelte';import StatusBadge from '$lib/components/StatusBadge.svelte';import { formatInstant,sentence } from '$lib/format';import { request,session } from '$lib/session.svelte';import { stepUp } from '$lib/oidc';
	import type { PlatformRoleResponse,PlatformUserResponse } from '$lib/generated/control-api';
	let roles=$state<PlatformRoleResponse[]>([]),users=$state<PlatformUserResponse[]>([]),userId=$state(''),role=$state('auditor'),reason=$state(''),error=$state(''),notice=$state(''),busy=$state(false);
	$effect(()=>{void load()});async function load(){try{[roles,users]=await Promise.all([request<PlatformRoleResponse[]>('/v1/platform/roles'),request<PlatformUserResponse[]>('/v1/platform/users')]);if(!userId&&users.length)userId=users[0].id;error=''}catch(cause){error=cause instanceof Error?cause.message:String(cause)}}
	async function grant(){busy=true;error='';notice='';try{await request('/v1/platform/roles',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({user_id:userId,role,reason_code:reason})});reason='';notice='Role granted.';await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
	async function revoke(item:PlatformRoleResponse){const reasonCode=window.prompt('Reason code for revocation');if(!reasonCode)return;busy=true;error='';try{await request(`/v1/platform/roles/${item.id}`,{method:'DELETE',headers:{'idempotency-key':crypto.randomUUID(),'if-match':`"platform-role-${item.id}-v${item.version}"`},body:JSON.stringify({reason_code:reasonCode})});notice='Role revoked.';await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
</script>
<svelte:head><title>Platform roles · MakersBrain</title></svelte:head><OperatorGuard><header class="page-header"><div><p class="eyebrow">Platform authority</p><h1>Role assignments</h1><p class="muted">Authorization is database-backed. The email bootstrap can establish only the first technical administrator.</p></div><button class="secondary" onclick={load}>Refresh</button></header><PlatformNav />{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice">{notice}</p>{/if}
	{#if !session.me?.recent_strong_authentication}<div class="card notice"><p>Grant and revoke require recent MFA or WebAuthn authentication.</p><button onclick={()=>stepUp('/platform/roles')}>Authenticate again with MFA</button></div>{/if}
	<form class="card form" onsubmit={(event)=>{event.preventDefault();void grant()}}><h2>Grant role</h2><label>Account<select bind:value={userId}>{#each users as user}<option value={user.id}>{user.email}</option>{/each}</select></label><label>Role<select bind:value={role}><option value="auditor">Auditor</option><option value="release_operator">Release operator</option><option value="privacy_reviewer">Privacy reviewer</option><option value="security_responder">Security responder</option><option value="technical_admin">Technical administrator</option></select></label><label>Reason code<input bind:value={reason} maxlength="100" required placeholder="approved_access_change" /></label><button disabled={busy||!session.me?.recent_strong_authentication}>Grant role</button></form>
	<section class="section card table-wrap">{#if roles.length===0}<div class="empty">No role assignments.</div>{:else}<table><thead><tr><th>Account</th><th>Role</th><th>Granted</th><th>State</th><th></th></tr></thead><tbody>{#each roles as item}<tr><td>{item.email}</td><td>{sentence(item.role)}</td><td>{formatInstant(item.granted_at)}<div class="muted">{item.grant_reason_code}</div></td><td><StatusBadge state={item.revoked_at?'revoked':'active'}/></td><td>{#if !item.revoked_at}<button class="danger" disabled={busy||!session.me?.recent_strong_authentication} onclick={()=>revoke(item)}>Revoke</button>{/if}</td></tr>{/each}</tbody></table>{/if}</section></OperatorGuard>
