<script lang="ts">
	import OperatorGuard from '$lib/components/OperatorGuard.svelte';
	import PlatformNav from '$lib/components/PlatformNav.svelte';
	import StatusBadge from '$lib/components/StatusBadge.svelte';
	import { formatInstant, sentence } from '$lib/format';
	import { request } from '$lib/session.svelte';
	import { stepUp } from '$lib/oidc';
	import type { LegalHoldResponse,PrivacyIncidentResponse,PrivacyOverviewResponse,PrivacyRequestResponse,ProcessorTaskResponse,RetentionRunCommandResponse } from '$lib/generated/control-api';
	let overview=$state<PrivacyOverviewResponse>(),requests=$state<PrivacyRequestResponse[]>([]),error=$state(''),notice=$state(''),busy=$state(false);
	let decisionCodes=$state<Record<string,string>>({});let policyVersion=$state('');
	$effect(()=>{void load()});
	async function load(){try{[overview,requests]=await Promise.all([request<PrivacyOverviewResponse>('/v1/platform/privacy'),request<PrivacyRequestResponse[]>('/v1/platform/privacy/requests')]);if(!policyVersion&&overview.retention_policies?.length)policyVersion=String(overview.retention_policies[0].version);error=''}catch(cause){error=cause instanceof Error?cause.message:String(cause)}}
	async function decide(item:PrivacyRequestResponse,decision:'review'|'approve'|'refuse'){busy=true;error='';notice='';try{await request(`/v1/platform/privacy/requests/${item.id}/decision`,{method:'POST',headers:{'idempotency-key':crypto.randomUUID(),'if-match':`"privacy-request-${item.id}-v${item.version}"`},body:JSON.stringify({decision,decision_code:decision==='review'?null:decisionCodes[item.id]})});notice=`Request moved to ${decision}.`;await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
	async function retention(dryRun:boolean){busy=true;error='';notice='';try{const result=await request<RetentionRunCommandResponse>('/v1/platform/privacy/retention-runs',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({policy_version:Number(policyVersion),dry_run:dryRun})});notice=`Retention ${dryRun?'dry run':'run'} queued as ${result.operation_id??result.command_id}.`;await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
	async function acknowledge(task:ProcessorTaskResponse,state:'acknowledged'|'not_applicable'){const evidenceRef=window.prompt(state==='acknowledged'?'Opaque processor evidence reference':'Reason code for not applicable');if(!evidenceRef)return;busy=true;error='';try{await request(`/v1/platform/privacy/processor-tasks/${task.id}/acknowledge`,{method:'POST',headers:{'idempotency-key':crypto.randomUUID(),'if-match':`"privacy-processor-task-${task.id}-v${task.version}"`},body:JSON.stringify({state,evidence_ref:evidenceRef})});notice='Processor evidence recorded.';await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
	async function createIncident(){const category=window.prompt('Bounded affected-data category key');if(!category)return;busy=true;error='';try{await request('/v1/platform/privacy/incidents',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({discovered_at:new Date().toISOString(),affected_categories:[category],containment_state:'investigating',risk_level:'undetermined'})});notice='Incident recorded. Assess controller notification promptly.';await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
	async function assessIncident(item:PrivacyIncidentResponse){const decisionRef=window.prompt('Opaque controller/DPO decision evidence reference');if(!decisionRef)return;const notificationRequired=window.confirm('Does the assessment require supervisory-authority notification?');busy=true;error='';try{await request(`/v1/platform/privacy/incidents/${item.id}/assessment`,{method:'POST',headers:{'idempotency-key':crypto.randomUUID(),'if-match':`"privacy-incident-${item.id}-v${item.version}"`},body:JSON.stringify({controller_awareness_at:notificationRequired?(item.controller_awareness_at??new Date().toISOString()):item.controller_awareness_at,containment_state:item.containment_state,risk_level:item.risk_level??'undetermined',notification_required:notificationRequired,decision_ref:decisionRef,authority_notification_ref:null,subject_notification_ref:null})});notice='Incident assessment recorded.';await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
	async function createHold(){const dataset=window.prompt('Exact inventory dataset key to hold');const reasonCode=window.prompt('Bounded reason code');const approvalRef=window.prompt('Opaque approval evidence reference');const expiresAt=window.prompt('Expiry in RFC 3339 (for example 2026-09-01T12:00:00Z)');if(!dataset||!reasonCode||!approvalRef||!expiresAt)return;busy=true;error='';try{await request('/v1/platform/privacy/legal-holds',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({datasets:[dataset],reason_code:reasonCode,approval_ref:approvalRef,expires_at:expiresAt})});notice='Scoped legal hold imposed.';await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
	async function releaseHold(item:LegalHoldResponse){const reasonCode=window.prompt('Bounded release reason code');if(!reasonCode)return;busy=true;error='';try{await request(`/v1/platform/privacy/legal-holds/${item.id}/release`,{method:'POST',headers:{'idempotency-key':crypto.randomUUID(),'if-match':`"privacy-legal-hold-${item.id}-v${item.version}"`},body:JSON.stringify({reason_code:reasonCode})});notice='Legal hold released.';await load()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
</script>
<svelte:head><title>Privacy governance · MakersBrain</title></svelte:head>
<OperatorGuard>
	<header class="page-header"><div><p class="eyebrow">Platform governance</p><h1>Privacy operations</h1><p class="muted">Controller approvals, rights requests, processor evidence and scoped retention.</p></div><button class="secondary" onclick={load}>Refresh</button></header><PlatformNav />
	{#if error}<div class="error" role="alert">{error} {#if error.includes('authentication')}<button class="secondary" onclick={()=>stepUp('/platform/privacy')}>Authenticate again with MFA</button>{/if}</div>{/if}{#if notice}<p class="notice">{notice}</p>{/if}
	{#if overview}<section class="grid summary"><article class="card"><span class="muted">Production personal data</span><StatusBadge state={overview.state.production_personal_data_allowed?'ready':'blocked'} label={overview.state.production_personal_data_allowed?'Allowed':'Blocked'} /></article><article class="card"><span class="muted">Controller</span><strong>{overview.state.controller_ref??'Not designated'}</strong></article><article class="card"><span class="muted">DPIA</span><strong>{overview.state.dpia_approval_ref??'Approval required'}</strong></article><article class="card"><span class="muted">Processors</span><strong>{overview.processors.filter((item)=>item.status==='approved').length}/{overview.processors.length} approved</strong></article></section>
	<section class="section card"><div class="section-header"><div><h2>Retention evidence</h2><p class="muted">Live deletion is unavailable until a controller-approved policy supplies explicit durations. Legal holds affect only named datasets.</p></div></div>{#if overview.retention_policies.length}<div class="actions"><label>Policy version<select bind:value={policyVersion}>{#each overview.retention_policies as policy}<option value={policy.version}>v{policy.version} · {sentence(policy.status)}</option>{/each}</select></label><button disabled={busy} onclick={()=>retention(true)}>Queue dry run</button><button class="danger" disabled={busy||overview.retention_policies.find((item)=>String(item.version)===policyVersion)?.status!=='approved'} onclick={()=>retention(false)}>Run approved deletion</button></div>{:else}<p class="empty">No versioned retention policy has been registered. No deletion duration has been inferred.</p>{/if}{#if overview.retention_runs.length}<div class="table-wrap"><table><thead><tr><th>Run</th><th>Policy</th><th>Mode</th><th>State</th><th>Created</th></tr></thead><tbody>{#each overview.retention_runs as run}<tr><td>{run.id}</td><td>{run.policy_version}</td><td>{run.dry_run?'Dry run':'Live'}</td><td><StatusBadge state={run.state}/></td><td>{formatInstant(run.created_at)}</td></tr>{/each}</tbody></table></div>{/if}</section>{/if}
	<section class="section"><div class="section-header"><div><h2>Data-subject requests</h2><p class="muted">Only designated privacy reviewers may decide requests. Approval/refusal remains blocked until a controller is recorded.</p></div></div><div class="card table-wrap">{#if requests.length===0}<div class="empty">No rights requests.</div>{:else}<table><thead><tr><th>Subject</th><th>Request</th><th>Deadline</th><th>State</th><th>Decision</th></tr></thead><tbody>{#each requests as item}<tr><td>{item.subject_email}</td><td>{sentence(item.request_type)}</td><td>{formatInstant(item.extended_due_at??item.due_at)}</td><td><StatusBadge state={item.status}/></td><td>{#if ['received','identity_verification'].includes(item.status)}<button disabled={busy} onclick={()=>decide(item,'review')}>Start review</button>{:else if item.status==='controller_review'}<div class="decision"><input bind:value={decisionCodes[item.id]} maxlength="100" placeholder="Decision code" aria-label="Decision code"/><button disabled={busy||!decisionCodes[item.id]} onclick={()=>decide(item,'approve')}>Approve</button><button class="danger" disabled={busy||!decisionCodes[item.id]} onclick={()=>decide(item,'refuse')}>Refuse</button></div>{:else}<span class="muted">{item.decision_code??'—'}</span>{/if}</td></tr>{/each}</tbody></table>{/if}</div></section>
	{#if overview?.processor_tasks?.length}<section class="section"><div class="section-header"><div><h2>Processor acknowledgements</h2><p class="muted">A rights request cannot complete until every applicable processor has evidence or an approved not-applicable reason.</p></div></div><div class="card table-wrap"><table><thead><tr><th>Request</th><th>Processor</th><th>Action</th><th>State</th><th>Evidence</th></tr></thead><tbody>{#each overview.processor_tasks as task}<tr><td>{task.data_subject_request_id}</td><td>{task.processor_key}</td><td>{sentence(task.action)}</td><td><StatusBadge state={task.state}/></td><td>{#if ['pending','sent','failed'].includes(task.state)}<div class="actions"><button disabled={busy} onclick={()=>acknowledge(task,'acknowledged')}>Record evidence</button><button class="secondary" disabled={busy} onclick={()=>acknowledge(task,'not_applicable')}>Not applicable</button></div>{:else}{task.acknowledgement_ref??task.safe_error_class??'—'}{/if}</td></tr>{/each}</tbody></table></div></section>{/if}
	{#if overview?.erasure_restore_replays?.length}<section class="section"><div class="section-header"><div><h2>Post-restore erasure evidence</h2><p class="muted">A restored workshop remains in maintenance until every listed processor location is complete.</p></div></div><div class="card table-wrap"><table><thead><tr><th>Recovery point</th><th>Required</th><th>Completed</th><th>State</th><th>Started</th></tr></thead><tbody>{#each overview.erasure_restore_replays as replay}<tr><td>{replay.recovery_point_id}</td><td>{replay.required_locations.join(', ')}</td><td>{replay.completed_locations.join(', ')||'—'}</td><td><StatusBadge state={replay.state} label={replay.safe_error_class?`${sentence(replay.state)} · ${sentence(replay.safe_error_class)}`:undefined}/></td><td>{formatInstant(replay.started_at??replay.created_at)}</td></tr>{/each}</tbody></table></div></section>{/if}
	{#if overview}<section class="section"><div class="section-header"><div><h2>Privacy and security incidents</h2><p class="muted">The authority deadline is calculated from recorded controller awareness; notification remains an explicit controller/DPO decision.</p></div><button disabled={busy} onclick={createIncident}>Record incident</button></div><div class="card table-wrap">{#if overview.incidents.length===0}<div class="empty">No privacy incidents recorded.</div>{:else}<table><thead><tr><th>Discovered</th><th>Containment</th><th>Risk</th><th>Authority deadline</th><th>Decision</th></tr></thead><tbody>{#each overview.incidents as item}<tr><td>{formatInstant(item.discovered_at)}</td><td><StatusBadge state={item.containment_state}/></td><td>{sentence(item.risk_level??'undetermined')}</td><td>{item.authority_deadline_at?formatInstant(item.authority_deadline_at):'Awaiting controller awareness'}</td><td><button disabled={busy||item.containment_state==='closed'} onclick={()=>assessIncident(item)}>Record assessment</button></td></tr>{/each}</tbody></table>{/if}</div></section>
	<section class="section"><div class="section-header"><div><h2>Scoped legal holds</h2><p class="muted">Holds require an approval reference, explicit inventory datasets and an expiry. Released holds cannot be reopened.</p></div><button disabled={busy} onclick={createHold}>Impose hold</button></div><div class="card table-wrap">{#if overview.legal_holds.length===0}<div class="empty">No legal holds recorded.</div>{:else}<table><thead><tr><th>Datasets</th><th>Reason</th><th>Expiry</th><th>State</th><th>Action</th></tr></thead><tbody>{#each overview.legal_holds as item}<tr><td>{item.scope.datasets.join(', ')}</td><td>{item.reason_code}</td><td>{formatInstant(item.expires_at)}</td><td><StatusBadge state={item.released_at?'released':(new Date(item.expires_at)<=new Date()?'expired':'active')}/></td><td>{#if !item.released_at}<button class="secondary" disabled={busy} onclick={()=>releaseHold(item)}>Release</button>{:else}<span class="muted">{item.release_reason_code}</span>{/if}</td></tr>{/each}</tbody></table>{/if}</div></section>{/if}
</OperatorGuard>
<style>.summary{grid-template-columns:repeat(4,minmax(0,1fr));margin-bottom:1rem}.summary article{display:grid;gap:.4rem}.actions{display:flex;gap:.75rem;align-items:end;flex-wrap:wrap}.decision{display:flex;gap:.4rem;min-width:24rem}.decision input{min-width:10rem}@media(max-width:800px){.summary{grid-template-columns:1fr 1fr}}</style>
